from rich.console import Console
con = Console()

dMedals = {
  1: ':1st_place_medal:',
  2: ':2nd_place_medal:',
  3: ':3rd_place_medal:'
}

lPlayerIcons = [
  '🛫',
  ':airplane_departure:',
  ':alarm_clock:',
  ':alien_monster:',
  '🤡'
  ]
l = [':alien:',
  ':ambulance:',
  ':anchor:',
  ':ant:',
  ':automobile:',
  ':avocado:',
  ':baby_bottle:',
  ':baby_chick:',
  ':baby_chick:',
  ':bacon:',
  ':badger:',
  ':balloon:',
  ':banana:',
  ':baseball:',
  ':basket:',
  ':basketball:',
  ':bat:',
  ':bathtub:',
  ':bear:',
  ':bird:',
  ':blossom:',
  ':blowfish:',
  ':bouquet:',
  ':bug:',
  ':butterfly:',
  ':cactus:',
  ':cherry_blossom:',
  ':cricket:',
  ':crocodile:',
  ':deciduous_tree:',
  ':dolphin:',
  ':dove:',
  ':dragon_face:',
  ':dragon:',
  ':duck:',
  ':eagle:',
  ':evergreen_tree:',
  ':fallen_leaf:',
  ':fish:',
  ':flamingo:',
  ':four_leaf_clover:',
  ':frog:',
  ':front-facing_baby_chick:',
  ':hatching_chick:',
  ':herb:',
  ':hibiscus:',
  ':honeybee:',
  ':lady_beetle:',
  ':leaf_fluttering_in_wind:',
  ':lizard:',
  ':maple_leaf:',
  ':microbe:',
  ':mosquito:',
  ':octopus:',
  ':palm_tree:',
  ':parrot:',
  ':peacock:',
  ':penguin:',
  ':rose:',
  ':rosette:',
  ':sauropod:',
  ':scorpion:',
  ':seedling:',
  ':shamrock:',
  ':shark:',
  ':sheaf_of_rice:',
  ':snail:',
  ':snake:',
  ':spider_web:',
  ':spider:',
  ':spiral_shell:',
  ':spouting_whale:',
  ':sunflower:',
  ':swan:',
  ':t-rex:',
  ':tropical_fish:',
  ':tulip:',
  ':turtle:',
  ':whale:',
  ':white_flower:',
  ':wilted_flower:'
]

if __name__ == '__main__':
  for i in range(len(lPlayerIcons)):
    con.print(f'{i+10} - {lPlayerIcons[i][1:-1]} - {lPlayerIcons[i]}')

  # for idx, icon in enumerate(lPlayerIcons, start=11):
  #   con.print(f'{idx}: {icon}')
